name: Java CI with Maven

on:
  
 pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn -B install --file pom.xml -DskipTests
    - name: Build image
      
      run: docker build -t springbootbackend:1.0 .
      
    - name: Anchore Container Scan
      uses: anchore/scan-action@v2.0.4
      with: 
        image: springbootbackend:1.0
        fail-build: true
        severity-cutoff: medium
